spring:
    application:
        name: asterisk-server
    security:
        user:
            name: ${SERVER_USER:USER123}
            password: ${SERVER_PASSWORD:USER123}

asterisk:
    client:
        host: ${AMI_HOST:192.168.0.110}
        port: ${AMI_PORT:5038}
        user: ${AMI_USER:test_ami}
        password: ${AMI_USER:test_ami}
        ssl: false
        encoding: ${AMI_CONNECTION_ENCODING:UTF-8}
        ping-interval: ${AMI_PING_INTERVAL:30s}


external-notifier:
    url: ${NOTIFICATION_URL:}
    events:
        -   name: NewState
            filters:
                -   name: Event
                    regex: (?:^Newstate$)
                -   name: Channel
                    regex: ^PJSIP/.*
                -   name: Context
                    value: from-internal
            fieldsMapping:
                channelstate: ChannelState
                channelstatedesc: ChannelStateDesc
                connectedlinenum: ConnectedLineNum
                calleridnum: CallerIdNum


management:
    info:
        git:
            enabled: true
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: "*"



logging:
    level:
        root: info
        ru.ivolkov.asterisk: debug

